### ISSUE TITLE
user variable is not used in router.js and App.vue

### ISSUE THREAD

**Issue by sinanerdem** [dabit3/production-ready-vue-authentication#2]
Hello dabit,

In router.js, you define the variable "user", assign a value if a user is signed in, but you never seem to use it. Linter complains about it.
```
let user;
    Vue.prototype.$Amplify.Auth.currentAuthenticatedUser().then(data => {
      if (data && data.signInUserSession) {
        user = data;
      }
```

Also in App.vue, you supply "user" as the parameter but it is not used inside the function.
```
Auth.currentAuthenticatedUser()
      .then(user => {
        this.signedIn = true
      })
      .catch(() => this.signedIn = false)
```

Are those intentional or forgotten there?

Amazon alias: erdesina
(Thanks for the tutorial by the way :))

**Comment by dabit3** [comment]
Hey, I've updated this project, I don't think user was being used.
